theme: minima
title: WELCOME TO MY HOUSE!
author: B MCGHEE
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is based off of random facts about my life. Things I love to do and my favorites.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
